version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    environment:
      - NODE_ENV=production
      - INSTANCE_NAME=app1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    environment:
      - NODE_ENV=production
      - INSTANCE_NAME=app2

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    environment:
      - NODE_ENV=production
      - INSTANCE_NAME=app3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge